package kz.fa.firebasewriter.model;

import java.util.Date;

/**
 * FireGoodsHistory generated by hbm2java
 */
public class FireGoodsHistory implements java.io.Serializable {

    private int id;
    private String oldId;
    private String newId;
    private Date dateUpdate;
    private Boolean ismerged;
    private Boolean ischecked;

    public FireGoodsHistory() {
    }

    public FireGoodsHistory(int id, String oldId, String newId) {
        this.id = id;
        this.oldId = oldId;
        this.newId = newId;
    }

    public FireGoodsHistory(int id, String oldId, String newId, Date dateUpdate, Boolean ismerged, Boolean ischecked) {
        this.id = id;
        this.oldId = oldId;
        this.newId = newId;
        this.dateUpdate = dateUpdate;
        this.ismerged = ismerged;
        this.ischecked = ischecked;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getOldId() {
        return this.oldId;
    }

    public void setOldId(String oldId) {
        this.oldId = oldId;
    }

    public String getNewId() {
        return this.newId;
    }

    public void setNewId(String newId) {
        this.newId = newId;
    }

    public Date getDateUpdate() {
        return this.dateUpdate;
    }

    public void setDateUpdate(Date dateUpdate) {
        this.dateUpdate = dateUpdate;
    }

    public Boolean getIsmerged() {
        return this.ismerged;
    }

    public void setIsmerged(Boolean ismerged) {
        this.ismerged = ismerged;
    }

    public Boolean getIschecked() {
        return this.ischecked;
    }

    public void setIschecked(Boolean ischecked) {
        this.ischecked = ischecked;
    }

}
